baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en" # Modify to change the default language/version of the site

title = "Accelerate the Modernization of critical applications with CAST Imaging"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= "false"
uglyurls = "true"
enableEmoji = true

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  #editURL = ""
  # Author of the site, will be used in meta information
  author = "CAST Software"
  # Description of the site, will be used in meta information
  description = "Accelerate the Modernization of critical applications with CAST Imaging"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"


[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
name = "<i class='fas fa-graduation-cap'></i> CAST Imaging Foundation Course"
url = "https://help.castsoftware.com/hc/en-us/articles/360013914719-CAST-University-for-Imaging"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fas fa-lightbulb'></i> CAST Imaging Pattern in the AWS Prescriptive Guidance Library"
url = "https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/analyze-and-visualize-software-architecture-in-cast-imaging.html"
weight = 20

[[menu.shortcuts]] 
name = "<i class='fas fa-tools'></i> Practical Guide to Accelerate Application Modernization"
url = "https://learn.castsoftware.com/download-wp-accelerating-application-refactoring_a-practical-guide"
weight = 30

[[menu.shortcuts]] 
name = "<i class='fas fa-play'></i> Practical Strategies & Guidance to Modernize Monoliths"
url = "https://learn.castsoftware.com/thank-you/monoliths-microservices_modernization-practical-strategies_guidance_follow-up"
weight = 40

#[[menu.shortcuts]] 
#name = "<i class='fas fa-graduation-cap'></i> Modernization Workshops"
#url = "https://awsworkshop.io"
#weight = 10
#
#[[menu.shortcuts]]
#name = "<i class='fas fa-tools'></i> AWS Builders Library"
#url = "https://aws.amazon.com/builders-library/"
#weight = 11
#
#[[menu.shortcuts]]
#name = "<i class='far fa-lightbulb'></i> Modernization with AWS"
#url = "https://aws.amazon.com/blogs/modernizing-with-aws/"
#weight = 20
#
#[[menu.shortcuts]]
#name = "<i class='fas fa-chalkboard-teacher'></i> EKS Workshop"
#url = "https://eksworkshop.com/"
#weight = 21
#
#[[menu.shortcuts]]
#name = "<i class='fas fa-chalkboard-teacher'></i> ECS Workshop"
#url = "https://ecsworkshop.com/"
#weight = 22
#
#[[menu.shortcuts]]
#name = "<i class='fas fa-chalkboard-teacher'></i> App Mesh Workshop"
#url = "https://www.appmeshworkshop.com/"
#weight = 23

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    hrefTargetBlank = true

[Languages] # Modify to change the language/version settings and/or version secondary extensions
[Languages.en]
title = "English"
weight = 1
languageName = "English"

[Languages.ee]
title = "Event Engine Setup"
weight = 2
languageName = "Event Engine Setup"